Repository atlp-rwanda/bravo-bn-fe, pull requests merged in 2022-09, with the labels that each got.

#28 feat(trip):Reject Trip Request
  package-lock.json
  src/components/dashboard/Dash.js
  src/components/dashboard/Footer.js
  src/components/dashboard/Navbar.js
  src/components/dashboard/PreLoader.js
  src/components/dashboard/RequestsTable.js
  src/components/dashboard/Sidebar.js
  src/components/dashboard/tripsRequest/Contents.js
  src/components/dashboard/tripsRequest/TripDetails.js
  src/components/dashboard/tripsRequest/TripRequests.js
  src/components/dashboard/tripsRequest/TripsContainer.js
  src/index.html
  src/redux/requests/requestSlice.js
  src/redux/requests/selectedRequestSlice.js
  src/redux/store.js
  src/routes/index.js
  src/styles/Navbar.scss
  src/styles/contents.scss
  src/styles/details.scss
  src/styles/index.scss
  src/styles/navbar.scss
  src/styles/sidebar.scss
  src/styles/users.scss
  src/tests/App.test.js
  src/tests/Reset.test.js
  src/tests/Respassword.test.js
  src/tests/login.test.js
  src/tests/signup.test.js
  src/tests/tripRequests.test.js
  src/views/Login.js
  src/views/Signup.js
  src/views/Trips.js
  webpack.config.js
Labels: Ready For Review

#48 Feature#182201689 Profile Information from request page
  src/components/NavDummy.js
  src/views/CreateRequest.jsx
Labels: approved

#46 Ft landing page
  src/assets/background.png
  src/components/Accommodation.js
  src/components/NavDummy.js
  src/components/dashboard/Sidebar.js
  src/redux/accommodationsSlice.js
  src/redux/store.js
  src/tests/tripRequests.test.js
  src/views/Home.js
Labels: Ready For Review

#39 #182201680 Users should be able to view and edit their profiles
  package-lock.json
  package.json
  src/assets/user.png
  src/components/Alert.js
  src/components/NavDummy.js
  src/components/Profile/EditProfileModel.js
  src/components/Profile/ViewProfileModel.js
  src/components/dashboard/RequestsTable.js
  src/redux/store.js
  src/styles/index.scss
  src/styles/profile.scss
  src/tests/App.test.js
  src/views/Login.js
Labels: Ready For Review

#41 #182201694 As a manager I should get a re-confirmation dialog for approving or rejecting travel requests
  src/components/NavDummy.js
  src/components/Profile/EditProfileModel.js
  src/components/dashboard/ContentElements.js
  src/components/dashboard/Sidebar.js
  src/components/dashboard/tripsRequest/ConfirmDialog.js
  src/components/dashboard/tripsRequest/TripDetails.js
  src/components/dashboard/tripsRequest/TripRequests.js
  src/redux/requests/requestSlice.js
  src/redux/store.js
  src/routes/index.js
  src/styles/details.scss
  src/styles/index.scss
  src/styles/navbar.scss
  src/tests/App.test.js
  src/tests/tripRequests.test.js
  src/views/Dasboard.js
  src/views/LandingDashboard.js
Labels: Ready For Review

#50 ft(404-page): page not found
  src/assets/not_found.svg
  src/components/Models.js
  src/components/NavDummy.js
  src/routes/index.js
  src/utils/PrivateRoutes.js
  src/views/Home.js
  src/views/Login.js
  src/views/NotFound.js
  src/views/Signup.js
Labels: Ready For Review

#38 #182201707 ft-delete-trip-request-comment
  package-lock.json
  src/components/Models.js
  src/utils/PrivateRoutes.js
  src/views/Book.js
  src/views/Login.js
Labels: Ready For Review

#37 Feature#182201690 Request updates notifications
  .circleci/config.yml
  package-lock.json
  package.json
  src/components/Models.js
  src/components/NavDummy.js
  src/components/Notifications/MenuPopover.js
  src/components/Notifications/NotificationPopover.js
  src/config/sockets.js
  src/redux/alertSlice.js
  src/redux/notificationSlice.js
  src/redux/store.js
  src/stories/Button.jsx
  src/stories/Button.stories.jsx
  src/tests/Button.stories.test.js
  src/tests/TripRequest.test.js
  src/tests/Updatemodal.test.js
  src/tests/alerts.test.js
  src/utils/PrivateRoutes.js
  src/views/Book.js
Labels: Ready For Review

#47 #182201692 Feature: fix create accomodation
  package-lock.json
  package.json
  src/components/GetLocation.js
  src/components/Map.js
  src/components/Renderm.js
  src/components/TextArea/TextArea.js
  src/components/TextArea/index.js
  src/components/dashboard/AccomodationTable.js
  src/components/dashboard/Sidebar.js
  src/index.html
  src/redux/mapSlice.js
  src/redux/requests/accomodationSlice.js
  src/redux/store.js
  src/routes/index.js
  src/styles/accommodation.scss
  src/styles/index.scss
  src/styles/map.scss
  src/styles/reset.scss
  src/styles/respassword.scss
  src/views/Accomodation.js
  src/views/Login.js
Labels: rebase
